##
 # @file Makefile
 # @brief makefile to build the ex7 program
 #
 # @dated 05-08-2018
 #

src = ex7.c
exe = exe
CC = gcc
CFLAG = -Wall	-g

default:
	$(CC) $(CFLAG) -o $(exe) $(src)
clean:
	rm	-f ex7